spring:
  datasource:
    profiles: prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhoulei
    password: Zl19950329
    url: jdbc:mysql://rm-wz990i1wpqv84rmweco.mysql.rds.aliyuncs.com:3306/productsell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell
#
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:/
#  file: D:/log/sell.log

wechat:
  mpAppId: wx66a605e685c95986
  mpAppSecret: 9fcb98faca12dc4df16128453f9324a9
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify

